import type { NextPage } from 'next'
import Head from 'next/head'
import Home from '../modules/Home'

const HomePage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Actum Digital | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Home />
      </main>
       
    </div>
  )
}

export default HomePage
